name: Typeset paper
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-paper:
    name: Typeset paper
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:latest
      options: --user root --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Apply vlna
        run: vlna -r -l -v KkSsVvZzOoUuAaIi main.md
      - name: Install Lilypond
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends lilypond
      - name: Typeset score with LyLuatex
        run: latexmk -lualatex -shell-escape -cd figures/lilypond-score.tex
      - name: Typeset paper
        run: latexmk -pdf -shell-escape main.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: |
            figures/
            markdownthemewitiko_csbulletin.sty
            main.bib
            main.tex
            main.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            main.pdf
